name: dev
services:
  webserver:
    image: ldg/webserver:${TAG}
    command: "webserver"
    ports:
      - "3000:3000"
    networks:
      - main-net

  frontend:
    image: ldg/frontend:${TAG}
    build:
      target: dev
    ports:
      - "8080:3000"
    environment:
      - API_URL=http://webserver:3000
    networks:
      - main-net
    depends_on:
      - webserver
    volumes:
      - ./../../frontend/src/app:/app/src/app:ro

networks:
  main-net: { }